// c: character，字
// p: pinyin，拼音
// sr: strokesRemaining，除去部首还剩几画

const wordsByAli = {
  "꒐": [
    { c: "ꒉ", p: "yy", sr: 1 },
    { c: "ꁌ", p: "pu", sr: 1 },
    { c: "ꑭ", p: "xy", sr: 1 },
    { c: "ꌅ", p: "nzy", sr: 1 },
    { c: "ꁼ", p: "nbiep", sr: 2 },
    { c: "ꁘ", p: "bbi", sr: 2 },
    { c: "ꑕ", p: "nyot", sr: 2 },
    { c: "ꈎ", p: "kut", sr: 2 },
    { c: "ꅍ", p: "ddu", sr: 2 },
    { c: "ꆳ", p: "hly", sr: 2 },
    { c: "ꑜ", p: "nyup", sr: 2 },
    { c: "ꐬ", p: "jjur", sr: 2 },
    { c: "ꅤ", p: "ndu", sr: 2 },
    { c: "ꁥ", p: "bbot", sr: 2 },
    { c: "ꀊ", p: "a", sr: 2 },
    { c: "ꃖ", p: "fo", sr: 2 },
    { c: "ꋪ", p: "zzyp", sr: 2 },
    { c: "ꏀ", p: "shyt", sr: 2 },
    { c: "ꀘ", p: "bi", sr: 2 },
    { c: "ꀿ", p: "pat", sr: 2 },
    { c: "ꂈ", p: "nbup", sr: 2 },
    { c: "ꑰ", p: "xyr", sr: 2 },
    { c: "ꐈ", p: "qot", sr: 3 },
    { c: "ꋰ", p: "nzip", sr: 3 },
    { c: "ꍓ", p: "zhe", sr: 3 },
    { c: "ꂓ", p: "hmi", sr: 3 },
    { c: "ꍝ", p: "zhy", sr: 3 },
    { c: "ꉛ", p: "hxe", sr: 3 },
    { c: "ꎺ", p: "shut", sr: 3 },
    { c: "ꇔ", p: "lyt", sr: 3 },
    { c: "ꉸ", p: "huop", sr: 3 },
    { c: "ꐩ", p: "jju", sr: 3 },
    { c: "ꄹ", p: "ddip", sr: 3 },
    { c: "ꄀ", p: "dit", sr: 3 },
    { c: "ꐚ", p: "jji", sr: 3 },
    { c: "ꎧ", p: "nry", sr: 3 },
    { c: "ꂀ", p: "nbap", sr: 3 },
    { c: "ꎗ", p: "nrap", sr: 3 },
    { c: "ꑛ", p: "nyu", sr: 3 },
    { c: "ꀠ", p: "ba", sr: 3 },
    { c: "ꀞ", p: "bat", sr: 3 },
    { c: "ꏌ", p: "ruop", sr: 3 },
    { c: "ꎨ", p: "nryp", sr: 3 },
    { c: "ꌃ", p: "nzyt", sr: 3 },
    { c: "ꅎ", p: "ddup", sr: 3 },
    { c: "ꃌ", p: "myp", sr: 3 },
    { c: "ꈨ", p: "gge", sr: 4 },
    { c: "ꀍ", p: "uo", sr: 4 },
    { c: "ꐆ", p: "quo", sr: 4 },
    { c: "ꀡ", p: "bap", sr: 4 },
    { c: "ꃚ", p: "fu", sr: 4 },
    { c: "ꊍ", p: "zit", sr: 4 },
    { c: "ꄼ", p: "ddiep", sr: 4 },
    { c: "ꈷ", p: "mguo", sr: 4 },
    { c: "ꆠ", p: "hla", sr: 4 },
    { c: "ꁧ", p: "bbo", sr: 4 },
    { c: "ꏙ", p: "rur", sr: 4 },
    { c: "ꃗ", p: "fop", sr: 4 },
    { c: "ꆿ", p: "lat", sr: 5 },
    { c: "ꍀ", p: "ssyt", sr: 5 },
    { c: "ꄻ", p: "ddie", sr: 5 },
    { c: "ꃿ", p: "vyr", sr: 5 },
    { c: "ꊒ", p: "zie", sr: 5 },
    { c: "ꒌ", p: "yyr", sr: 5 },
    { c: "ꏔ", p: "rut", sr: 6 },
    { c: "ꃨ", p: "vie", sr: 6 }
  ],

  "꒑（꒒）": [
    { c: "ꆹ", p: "li", sr: 1 },
    { c: "ꆾ", p: "liep", sr: 1 },
    { c: "ꈤ", p: "ggo", sr: 1 },
    { c: "ꀮ", p: "bu", sr: 1 },
    { c: "ꐳ", p: "nji", sr: 1 },
    { c: "ꐱ", p: "njit", sr: 1 },
    { c: "ꉬ", p: "nge", sr: 2 },
    { c: "ꄌ", p: "duo", sr: 2 },
    { c: "ꑠ", p: "xip", sr: 2 },
    { c: "ꈐ", p: "ku", sr: 2 },
    { c: "ꈓ", p: "kur", sr: 2 },
    { c: "ꄔ", p: "dut", sr: 2 },
    { c: "ꐏ", p: "qup", sr: 2 },
    { c: "ꄠ", p: "tiep", sr: 2 },
    { c: "ꃅ", p: "mu", sr: 2 },
    { c: "ꎼ", p: "shu", sr: 2 },
    { c: "ꃰ", p: "vo", sr: 2 },
    { c: "ꉪ", p: "ngop", sr: 2 },
    { c: "ꌎ", p: "sie", sr: 2 },
    { c: "ꍌ", p: "zhuop", sr: 2 },
    { c: "ꋡ", p: "zzep", sr: 2 },
    { c: "ꈞ", p: "gguot", sr: 2 },
    { c: "ꈖ", p: "ggi", sr: 2 },
    { c: "ꃂ", p: "me", sr: 2 },
    { c: "ꃦ", p: "viet", sr: 2 },
    { c: "ꆻ", p: "liet", sr: 3 },
    { c: "ꉊ", p: "hxiet", sr: 3 },
    { c: "ꁣ", p: "bbuo", sr: 3 },
    { c: "ꅓ", p: "ndi", sr: 3 },
    { c: "ꇸ", p: "kit", sr: 3 },
    { c: "ꄜ", p: "ti", sr: 3 },
    { c: "ꃈ", p: "mur", sr: 3 },
    { c: "ꇬ", p: "go", sr: 3 },
    { c: "ꂪ", p: "hmy", sr: 3 },
    { c: "ꃃ", p: "mut", sr: 3 },
    { c: "ꌉ", p: "sit", sr: 3 },
    { c: "ꉣ", p: "ngap", sr: 3 },
    { c: "ꁫ", p: "bbep", sr: 3 },
    { c: "ꐂ", p: "qie", sr: 3 },
    { c: "ꌠ", p: "su", sr: 3 },
    { c: "ꆦ", p: "hlo", sr: 3 },
    { c: "ꅚ", p: "ndap", sr: 3 },
    { c: "ꊤ", p: "zu", sr: 3 },
    { c: "ꂖ", p: "hmie", sr: 3 },
    { c: "ꁅ", p: "puop", sr: 3 },
    { c: "ꐄ", p: "quot", sr: 3 },
    { c: "ꒄ", p: "yup", sr: 3 },
    { c: "ꊚ", p: "zuop", sr: 3 },
    { c: "ꌐ", p: "sat", sr: 3 },
    { c: "ꂥ", p: "hmu", sr: 4 },
    { c: "ꄮ", p: "te", sr: 4 },
    { c: "ꍿ", p: "rruo", sr: 4 },
    { c: "ꎀ", p: "rrot", sr: 4 },
    { c: "ꄨ", p: "tuop", sr: 4 },
    { c: "ꃑ", p: "fat", sr: 4 },
    { c: "ꎮ", p: "shap", sr: 4 },
    { c: "ꑐ", p: "nyie", sr: 4 },
    { c: "ꌒ", p: "sa", sr: 5 },
    { c: "ꌣ", p: "sur", sr: 5 },
    { c: "ꅿ", p: "ni", sr: 5 },
    { c: "ꍹ", p: "chyp", sr: 6 }
  ],

  "꒓": [
    { c: "ꑍ", p: "nyip", sr: 1 },
    { c: "ꊰ", p: "ci", sr: 1 },
    { c: "ꈉ", p: "kop", sr: 1 },
    { c: "ꇁ", p: "la", sr: 1 },
    { c: "ꉮ", p: "hit", sr: 1 },
    { c: "ꈘ", p: "ggie", sr: 1 },
    { c: "ꌕ", p: "suo", sr: 2 },
    { c: "ꌖ", p: "suop", sr: 2 },
    { c: "ꌌ", p: "sip", sr: 2 },
    { c: "ꉜ", p: "hxep", sr: 2 },
    { c: "ꉷ", p: "huo", sr: 2 },
    { c: "ꂛ", p: "hmap", sr: 2 },
    { c: "ꄙ", p: "dur", sr: 2 },
    { c: "ꅪ", p: "hni", sr: 2 },
    { c: "ꄯ", p: "tep", sr: 2 },
    { c: "ꂿ", p: "mo", sr: 2 },
    { c: "ꍣ", p: "cha", sr: 2 },
    { c: "ꍡ", p: "chat", sr: 2 },
    { c: "ꍋ", p: "zhuo", sr: 2 },
    { c: "ꍍ", p: "zhot", sr: 2 },
    { c: "ꅫ", p: "hnip", sr: 2 },
    { c: "ꏆ", p: "rat", sr: 2 },
    { c: "ꏶ", p: "jyt", sr: 2 },
    { c: "ꊌ", p: "wep", sr: 2 },
    { c: "ꇅ", p: "luo", sr: 2 },
    { c: "ꋣ", p: "zzu", sr: 2 },
    { c: "ꀆ", p: "ie", sr: 2 },
    { c: "ꊵ", p: "ciep", sr: 2 },
    { c: "ꊮ", p: "cit", sr: 2 },
    { c: "ꑩ", p: "xo", sr: 2 },
    { c: "ꌸ", p: "ssop", sr: 2 },
    { c: "ꉾ", p: "he", sr: 2 },
    { c: "ꎈ", p: "rrut", sr: 2 },
    { c: "ꏋ", p: "ruo", sr: 2 },
    { c: "ꊲ", p: "ciet", sr: 2 },
    { c: "ꈱ", p: "mgie", sr: 2 },
    { c: "ꎑ", p: "rryp", sr: 2 },
    { c: "ꍗ", p: "zhu", sr: 2 },
    { c: "ꑌ", p: "nyi", sr: 3 },
    { c: "ꅨ", p: "hnit", sr: 3 },
    { c: "ꉵ", p: "huot", sr: 3 },
    { c: "ꌜ", p: "se", sr: 3 },
    { c: "ꃘ", p: "fut", sr: 3 },
    { c: "ꎭ", p: "sha", sr: 3 },
    { c: "ꋦ", p: "zzur", sr: 3 },
    { c: "ꋽ", p: "nze", sr: 3 },
    { c: "ꊓ", p: "ziep", sr: 3 },
    { c: "ꅬ", p: "hniet", sr: 3 },
    { c: "ꐺ", p: "njuo", sr: 3 },
    { c: "ꐥ", p: "jjo", sr: 3 },
    { c: "ꂵ", p: "mat", sr: 3 },
    { c: "ꈴ", p: "mga", sr: 3 },
    { c: "ꍏ", p: "zho", sr: 3 },
    { c: "ꑪ", p: "xop", sr: 3 },
    { c: "ꀵ", p: "byp", sr: 3 },
    { c: "ꍽ", p: "rra", sr: 3 },
    { c: "ꊆ", p: "wuop", sr: 3 },
    { c: "ꁹ", p: "nbip", sr: 3 },
    { c: "ꅄ", p: "ddot", sr: 4 },
    { c: "ꃺ", p: "vyt", sr: 4 },
    { c: "ꊋ", p: "we", sr: 4 },
    { c: "ꎸ", p: "she", sr: 4 },
    { c: "ꎹ", p: "shep", sr: 4 },
    { c: "ꁓ", p: "pyp", sr: 4 },
    { c: "ꎡ", p: "nru", sr: 4 },
    { c: "ꍥ", p: "chuot", sr: 4 },
    { c: "ꊠ", p: "ze", sr: 4 },
    { c: "ꁶ", p: "nbit", sr: 5 },
    { c: "ꋷ", p: "nzap", sr: 5 },
    { c: "ꐰ", p: "jjyp", sr: 6 }
  ],

  "꒔": [
    { c: "ꋍ", p: "cyp", sr: 0 },
    { c: "ꇰ", p: "ge", sr: 1 },
    { c: "ꉘ", p: "hxo", sr: 1 },
    { c: "ꌺ", p: "sse", sr: 1 },
    { c: "ꆈ", p: "nuo", sr: 1 },
    { c: "ꄐ", p: "dop", sr: 1 },
    { c: "ꇉ", p: "lo", sr: 1 },
    { c: "ꈢ", p: "ggot", sr: 1 },
    { c: "ꀴ", p: "by", sr: 1 },
    { c: "ꉰ", p: "hie", sr: 1 },
    { c: "ꊻ", p: "cuo", sr: 1 },
    { c: "ꆏ", p: "ne", sr: 2 },
    { c: "ꄸ", p: "ddi", sr: 2 },
    { c: "ꑽ", p: "yot", sr: 2 },
    { c: "ꉐ", p: "hxa", sr: 2 },
    { c: "ꃏ", p: "fi", sr: 2 },
    { c: "ꅡ", p: "ndep", sr: 2 },
    { c: "ꁍ", p: "pup", sr: 2 },
    { c: "ꁵ", p: "bbyp", sr: 2 },
    { c: "ꂑ", p: "hmit", sr: 2 },
    { c: "ꁴ", p: "bby", sr: 2 },
    { c: "ꑴ", p: "yip", sr: 2 },
    { c: "ꄩ", p: "tot", sr: 2 },
    { c: "ꆃ", p: "niep", sr: 2 },
    { c: "ꎪ", p: "nryr", sr: 2 },
    { c: "ꒆ", p: "yur", sr: 2 },
    { c: "ꃭ", p: "vap", sr: 2 },
    { c: "ꄒ", p: "de", sr: 2 },
    { c: "ꄟ", p: "tie", sr: 2 },
    { c: "ꄚ", p: "tit", sr: 2 },
    { c: "ꍬ", p: "chop", sr: 2 },
    { c: "ꀋ", p: "ap", sr: 2 },
    { c: "ꋴ", p: "nzat", sr: 2 },
    { c: "ꆴ", p: "hlyp", sr: 2 },
    { c: "ꑇ", p: "njyp", sr: 2 },
    { c: "ꈅ", p: "kuop", sr: 2 },
    { c: "ꃴ", p: "vut", sr: 2 },
    { c: "ꏝ", p: "ryp", sr: 2 },
    { c: "ꑗ", p: "nyo", sr: 2 },
    { c: "ꆑ", p: "nut", sr: 2 },
    { c: "ꀔ", p: "e", sr: 2 },
    { c: "ꀲ", p: "byt", sr: 2 },
    { c: "ꆔ", p: "nup", sr: 3 },
    { c: "ꆓ", p: "nu", sr: 3 },
    { c: "ꃽ", p: "vyp", sr: 3 },
    { c: "ꑸ", p: "yiep", sr: 3 },
    { c: "ꂻ", p: "muo", sr: 3 },
    { c: "ꑻ", p: "yuo", sr: 3 },
    { c: "ꍚ", p: "zhur", sr: 3 },
    { c: "ꍧ", p: "chuo", sr: 3 },
    { c: "ꉞ", p: "ngie", sr: 3 },
    { c: "ꋶ", p: "nza", sr: 3 },
    { c: "ꋭ", p: "nzit", sr: 3 },
    { c: "ꁲ", p: "bbyt", sr: 3 },
    { c: "ꉑ", p: "hxap", sr: 4 },
    { c: "ꈩ", p: "ggep", sr: 4 },
    { c: "ꌙ", p: "so", sr: 4 },
    { c: "ꈈ", p: "ko", sr: 4 },
    { c: "ꈄ", p: "kuo", sr: 4 },
    { c: "ꆖ", p: "nur", sr: 4 },
    { c: "ꑹ", p: "yuot", sr: 4 },
    { c: "ꄵ", p: "tur", sr: 4 },
    { c: "ꋤ", p: "zzup", sr: 4 },
    { c: "ꂘ", p: "hmat", sr: 4 },
    { c: "ꍩ", p: "chot", sr: 4 },
    { c: "ꅖ", p: "ndie", sr: 4 },
    { c: "ꉟ", p: "ngiep", sr: 4 },
    { c: "ꈦ", p: "gget", sr: 5 },
    { c: "ꏤ", p: "jiet", sr: 5 }
  ],

  "꒕": [
    { c: "ꀈ", p: "at", sr: 1 },
    { c: "ꄝ", p: "tip", sr: 1 },
    { c: "ꅲ", p: "hna", sr: 1 },
    { c: "ꈪ", p: "ggut", sr: 1 },
    { c: "ꇽ", p: "kie", sr: 1 },
    { c: "ꋻ", p: "nzop", sr: 1 },
    { c: "ꇝ", p: "gip", sr: 2 },
    { c: "ꑷ", p: "yie", sr: 2 },
    { c: "ꂗ", p: "hmiep", sr: 2 },
    { c: "ꃝ", p: "fur", sr: 2 },
    { c: "ꏻ", p: "jyr", sr: 2 },
    { c: "ꋩ", p: "zzy", sr: 2 },
    { c: "ꆷ", p: "lit", sr: 2 },
    { c: "ꁮ", p: "bbu", sr: 2 },
    { c: "ꉱ", p: "hat", sr: 2 },
    { c: "ꆝ", p: "hliep", sr: 2 },
    { c: "ꌬ", p: "ssi", sr: 2 },
    { c: "ꀙ", p: "bip", sr: 2 },
    { c: "ꊡ", p: "zep", sr: 2 },
    { c: "ꃉ", p: "myt", sr: 2 },
    { c: "ꃱ", p: "vop", sr: 2 },
    { c: "ꃷ", p: "vup", sr: 2 },
    { c: "ꈆ", p: "kot", sr: 3 },
    { c: "ꅰ", p: "hnat", sr: 3 },
    { c: "ꎄ", p: "rret", sr: 3 },
    { c: "ꍑ", p: "zhet", sr: 3 },
    { c: "ꎓ", p: "rryr", sr: 3 },
    { c: "ꌵ", p: "ssot", sr: 3 },
    { c: "ꋝ", p: "zzo", sr: 3 },
    { c: "ꐣ", p: "jjot", sr: 3 },
    { c: "ꎛ", p: "nret", sr: 3 },
    { c: "ꋓ", p: "zzip", sr: 4 },
    { c: "ꏜ", p: "ry", sr: 4 },
    { c: "ꌭ", p: "ssip", sr: 4 },
    { c: "ꊔ", p: "zat", sr: 4 },
    { c: "ꍻ", p: "chyr", sr: 4 },
    { c: "ꇡ", p: "giep", sr: 4 },
    { c: "ꅇ", p: "ddop", sr: 5 },
    { c: "ꌪ", p: "ssit", sr: 5 }
  ],

  "꒖": [
    { c: "ꎐ", p: "rry", sr: 1 },
    { c: "ꈥ", p: "ggop", sr: 1 },
    { c: "ꏃ", p: "shyp", sr: 1 },
    { c: "ꉢ", p: "nga", sr: 1 },
    { c: "ꑊ", p: "nyit", sr: 2 },
    { c: "ꅮ", p: "hnie", sr: 2 },
    { c: "ꑆ", p: "njy", sr: 2 },
    { c: "ꌧ", p: "syp", sr: 2 },
    { c: "ꎥ", p: "nryt", sr: 2 },
    { c: "ꅛ", p: "ndot", sr: 2 },
    { c: "ꈝ", p: "ggap", sr: 2 },
    { c: "ꇌ", p: "le", sr: 2 },
    { c: "ꅝ", p: "ndo", sr: 2 },
    { c: "ꈚ", p: "ggat", sr: 2 },
    { c: "ꈵ", p: "mgap", sr: 2 },
    { c: "ꎝ", p: "nre", sr: 2 },
    { c: "ꊝ", p: "zo", sr: 2 },
    { c: "ꃠ", p: "fy", sr: 2 },
    { c: "ꂝ", p: "hmuo", sr: 2 },
    { c: "ꃞ", p: "fyt", sr: 2 },
    { c: "ꄧ", p: "tuo", sr: 3 },
    { c: "ꎎ", p: "rryt", sr: 3 },
    { c: "ꌼ", p: "ssut", sr: 3 },
    { c: "ꅞ", p: "ndop", sr: 4 },
    { c: "ꌿ", p: "ssup", sr: 4 },
    { c: "ꎶ", p: "shet", sr: 4 },
    { c: "ꏦ", p: "jie", sr: 4 },
    { c: "ꂫ", p: "hmyp", sr: 6 }
  ],

  "꒗（꒘）": [
    { c: "ꇱ", p: "gep", sr: 1 },
    { c: "ꄂ", p: "di", sr: 1 },
    { c: "ꄏ", p: "do", sr: 1 },
    { c: "ꂰ", p: "mi", sr: 1 },
    { c: "ꆫ", p: "hlut", sr: 2 },
    { c: "ꁯ", p: "bbup", sr: 2 },
    { c: "ꆐ", p: "nep", sr: 2 },
    { c: "ꆍ", p: "nop", sr: 2 },
    { c: "ꃐ", p: "fip", sr: 2 },
    { c: "ꅙ", p: "nda", sr: 2 },
    { c: "ꇮ", p: "get", sr: 2 },
    { c: "ꅗ", p: "ndat", sr: 2 },
    { c: "ꋇ", p: "cup", sr: 2 },
    { c: "ꑉ", p: "njyr", sr: 2 },
    { c: "ꆅ", p: "na", sr: 2 },
    { c: "ꍂ", p: "ssy", sr: 2 },
    { c: "ꆶ", p: "hlyr", sr: 2 },
    { c: "ꂱ", p: "mip", sr: 2 },
    { c: "ꂴ", p: "miep", sr: 2 },
    { c: "ꒁ", p: "yut", sr: 2 },
    { c: "ꂎ", p: "nbyp", sr: 2 },
    { c: "ꑃ", p: "njur", sr: 2 },
    { c: "ꂞ", p: "hmuop", sr: 2 },
    { c: "ꄫ", p: "to", sr: 3 },
    { c: "ꈂ", p: "kap", sr: 3 },
    { c: "ꇂ", p: "lap", sr: 3 },
    { c: "ꅸ", p: "hnop", sr: 3 },
    { c: "ꅼ", p: "hnut", sr: 3 },
    { c: "ꅶ", p: "hnot", sr: 3 },
    { c: "ꌾ", p: "ssu", sr: 3 },
    { c: "ꍶ", p: "chyt", sr: 3 },
    { c: "ꅯ", p: "hniep", sr: 3 },
    { c: "ꆆ", p: "nap", sr: 3 },
    { c: "ꆌ", p: "no", sr: 4 }
  ],

  "꒙": [
    { c: "ꉆ", p: "hxit", sr: 1 },
    { c: "ꇗ", p: "lyp", sr: 1 },
    { c: "ꂚ", p: "hma", sr: 1 },
    { c: "ꏢ", p: "ji", sr: 2 },
    { c: "ꈙ", p: "ggiep", sr: 2 },
    { c: "ꇖ", p: "ly", sr: 2 },
    { c: "ꇍ", p: "lep", sr: 2 },
    { c: "ꊂ", p: "wa", sr: 2 },
    { c: "ꊃ", p: "wap", sr: 2 },
    { c: "ꁱ", p: "bbur", sr: 2 },
    { c: "ꍸ", p: "chy", sr: 2 },
    { c: "ꄓ", p: "dep", sr: 2 },
    { c: "ꎇ", p: "rrep", sr: 2 },
    { c: "ꍫ", p: "cho", sr: 2 },
    { c: "ꍞ", p: "zhyp", sr: 2 },
    { c: "ꋗ", p: "zziep", sr: 3 },
    { c: "ꄶ", p: "ddit", sr: 3 },
    { c: "ꎱ", p: "shuop", sr: 3 },
    { c: "ꃓ", p: "fa", sr: 3 },
    { c: "ꋐ", p: "zzit", sr: 3 },
    { c: "ꃥ", p: "vip", sr: 3 },
    { c: "ꁪ", p: "bbe", sr: 3 },
    { c: "ꅑ", p: "ndit", sr: 4 },
    { c: "ꃔ", p: "fap", sr: 4 },
    { c: "ꌯ", p: "ssie", sr: 4 },
    { c: "ꐭ", p: "jjyt", sr: 4 },
    { c: "ꌰ", p: "ssiep", sr: 4 },
    { c: "ꍈ", p: "zha", sr: 6 },
  ],

  "꒚（꒛）": [
    { c: "ꇙ", p: "lyr", sr: 0 },
    { c: "ꂢ", p: "hmop", sr: 1 },
    { c: "ꌗ", p: "sot", sr: 2 },
    { c: "ꑄ", p: "njyt", sr: 2 },
    { c: "ꍛ", p: "zhyt", sr: 2 },
    { c: "ꏚ", p: "ryt", sr: 2 },
    { c: "ꈜ", p: "gga", sr: 3 },
    { c: "ꌚ", p: "sop", sr: 4 },
    { c: "ꌝ", p: "sep", sr: 4 },
    { c: "ꁬ", p: "bbut", sr: 4 },
    { c: "ꊨ", p: "zyt", sr: 4 },
    { c: "ꏣ", p: "jip", sr: 4 }
  ],

  "꒜（꒝、꒞）": [
    { c: "ꃀ", p: "mop", sr: 0 },
    { c: "ꁊ", p: "put", sr: 0 },
    { c: "ꇜ", p: "gi", sr: 1 },
    { c: "ꆡ", p: "hlap", sr: 1 },
    { c: "ꊐ", p: "zip", sr: 1 },
    { c: "ꑿ", p: "yo", sr: 1 },
    { c: "ꏳ", p: "jup", sr: 1 },
    { c: "ꌓ", p: "sap", sr: 1 },
    { c: "ꎚ", p: "nrop", sr: 1 },
    { c: "ꎙ", p: "nro", sr: 2 },
    { c: "ꇚ", p: "git", sr: 2 },
    { c: "ꊹ", p: "cap", sr: 2 },
    { c: "ꂅ", p: "nbut", sr: 2 },
    { c: "ꂁ", p: "nbot", sr: 2 },
    { c: "ꍉ", p: "zhap", sr: 2 },
    { c: "ꍵ", p: "chur", sr: 2 },
    { c: "ꑳ", p: "yi", sr: 3 },
    { c: "ꎃ", p: "rrop", sr: 3 },
    { c: "ꀣ", p: "buo", sr: 3 },
    { c: "ꑼ", p: "yuop", sr: 3 },
    { c: "ꇃ", p: "luot", sr: 3 },
    { c: "ꍃ", p: "ssyp", sr: 5 },
  ],

  "꒟（꒠）": [
    { c: "ꉔ", p: "hxuo", sr: 0 },
    { c: "ꀯ", p: "bup", sr: 1 },
    { c: "ꏲ", p: "ju", sr: 1 },
    { c: "ꃤ", p: "vi", sr: 1 },
    { c: "ꉌ", p: "hxie", sr: 1 },
    { c: "ꉧ", p: "ngot", sr: 1 },
    { c: "ꄡ", p: "tat", sr: 1 },
    { c: "ꎆ", p: "rre", sr: 1 },
    { c: "ꉖ", p: "hxot", sr: 1 },
    { c: "ꏸ", p: "jy", sr: 1 },
    { c: "ꄅ", p: "die", sr: 2 },
    { c: "ꅉ", p: "dde", sr: 2 },
    { c: "ꐾ", p: "njop", sr: 2 },
    { c: "ꎍ", p: "rrur", sr: 2 },
    { c: "ꐦ", p: "jjop", sr: 2 },
    { c: "ꏗ", p: "rup", sr: 2 },
    { c: "ꏹ", p: "jyp", sr: 2 },
    { c: "ꍠ", p: "zhyr", sr: 2 },
    { c: "ꎲ", p: "shot", sr: 2 },
    { c: "ꑁ", p: "njup", sr: 2 },
    { c: "ꁝ", p: "bbiep", sr: 2 },
    { c: "ꑀ", p: "nju", sr: 3 },
    { c: "ꉂ", p: "mgu", sr: 3 },
    { c: "ꃶ", p: "vu", sr: 3 },
    { c: "ꏧ", p: "jiep", sr: 3 },
    { c: "ꆣ", p: "hluo", sr: 3 },
    { c: "ꅺ", p: "hne", sr: 3 },
    { c: "ꄤ", p: "tap", sr: 3 },
    { c: "ꇿ", p: "kat", sr: 3 },
    { c: "ꊅ", p: "wuo", sr: 3 },
    { c: "ꁜ", p: "bbie", sr: 3 },
    { c: "ꏅ", p: "shyr", sr: 4 },
    { c: "ꑑ", p: "nyiep", sr: 4 },
    { c: "ꑎ", p: "nyiet", sr: 4 },
    { c: "ꁞ", p: "bbat", sr: 4 },
    { c: "ꅻ", p: "hnep", sr: 4 },
    { c: "ꎋ", p: "rrup", sr: 4 },
    { c: "ꁉ", p: "pop", sr: 4 },
    { c: "ꁄ", p: "puo", sr: 5 },
    { c: "ꈾ", p: "mge", sr: 5 },
    { c: "ꐡ", p: "jjuo", sr: 5 },
  ],
  
  "꒡（꒢、꒣）": [
    { c: "ꌩ", p: "syr", sr: 1 },
    { c: "ꌦ", p: "sy", sr: 1 },
    { c: "ꐔ", p: "qy", sr: 1 },
    { c: "ꇤ", p: "ga", sr: 1 },
    { c: "ꈑ", p: "kup", sr: 1 },
    { c: "ꋊ", p: "cyt", sr: 1 },
    { c: "ꃋ", p: "my", sr: 2 },
    { c: "ꌤ", p: "syt", sr: 2 },
    { c: "ꑮ", p: "xyp", sr: 2 },
    { c: "ꃢ", p: "vit", sr: 2 },
    { c: "ꐕ", p: "qyp", sr: 2 },
    { c: "ꒀ", p: "yop", sr: 2 },
    { c: "ꇠ", p: "gie", sr: 2 },
    { c: "ꆱ", p: "hlyt", sr: 2 },
    { c: "ꏪ", p: "juo", sr: 2 },
    { c: "ꏯ", p: "jop", sr: 2 },
    { c: "ꈊ", p: "ket", sr: 2 },
    { c: "ꌞ", p: "sut", sr: 2 },
    { c: "ꉒ", p: "hxuot", sr: 2 },
    { c: "ꉕ", p: "hxuop", sr: 2 },
    { c: "ꐢ", p: "jjuop", sr: 2 },
    { c: "ꃡ", p: "fyp", sr: 2 },
    { c: "ꂨ", p: "hmur", sr: 3 },
    { c: "ꈍ", p: "kep", sr: 3 },
    { c: "ꃼ", p: "vy", sr: 3 },
    { c: "ꁈ", p: "po", sr: 3 },
    { c: "ꐜ", p: "jjiet", sr: 3 },
    { c: "ꑫ", p: "xyt", sr: 3 },
    { c: "ꉃ", p: "mgup", sr: 3 },
    { c: "ꆗ", p: "hlit", sr: 3 },
    { c: "ꆙ", p: "hli", sr: 3 },
    { c: "ꒃ", p: "yu", sr: 3 },
    { c: "ꋞ", p: "zzop", sr: 3 },
    { c: "ꇢ", p: "gat", sr: 3 },
    { c: "ꊗ", p: "zap", sr: 3 },
    { c: "ꊏ", p: "zi", sr: 3 },
    { c: "ꊥ", p: "zup", sr: 3 },
    { c: "ꏠ", p: "jit", sr: 3 },
    { c: "ꇞ", p: "giet", sr: 3 },
    { c: "ꐟ", p: "jjiep", sr: 4 },
    { c: "ꐘ", p: "jjit", sr: 4 },
    { c: "ꒇ", p: "yyt", sr: 4 },
    { c: "ꋹ", p: "nzuo", sr: 4 },
    { c: "ꎴ", p: "sho", sr: 4 },
    { c: "ꅆ", p: "ddo", sr: 5 },
    { c: "ꇇ", p: "lot", sr: 5 },
    { c: "ꎢ", p: "nrup", sr: 5 },
    { c: "ꑔ", p: "nyuop", sr: 5 }
  ],

  "꒤（꒥、꒦）": [
    { c: "ꇴ", p: "gu", sr: 1 },
    { c: "ꅐ", p: "ddur", sr: 1 },
    { c: "ꏵ", p: "jur", sr: 1 },
    { c: "ꉅ", p: "mgur", sr: 1 },
    { c: "ꉠ", p: "ngat", sr: 1 },
    { c: "ꐴ", p: "njip", sr: 1 },
    { c: "ꃮ", p: "vot", sr: 1 },
    { c: "ꃬ", p: "va", sr: 1 },
    { c: "ꋬ", p: "zzyr", sr: 1 },
    { c: "ꈠ", p: "gguo", sr: 1 },
    { c: "ꋳ", p: "nziep", sr: 1 },
    { c: "ꀀ", p: "it", sr: 2 },
    { c: "ꀂ", p: "i", sr: 2 },
    { c: "ꌂ", p: "nzur", sr: 2 },
    { c: "ꁁ", p: "pa", sr: 2 },
    { c: "ꁂ", p: "pap", sr: 2 },
    { c: "ꇆ", p: "luop", sr: 2 },
    { c: "ꊽ", p: "cot", sr: 2 },
    { c: "ꊀ", p: "wat", sr: 2 },
    { c: "ꀱ", p: "bur", sr: 2 },
    { c: "ꐞ", p: "jjie", sr: 2 },
    { c: "ꌈ", p: "nzyr", sr: 3 },
    { c: "ꐇ", p: "quop", sr: 3 },
    { c: "ꇷ", p: "gur", sr: 3 },
    { c: "ꄇ", p: "dat", sr: 3 },
    { c: "ꂹ", p: "muot", sr: 3 },
    { c: "ꉀ", p: "mgut", sr: 4 },
    { c: "ꋲ", p: "nzie", sr: 4 },
    { c: "ꍔ", p: "zhep", sr: 5 },
    { c: "ꂍ", p: "nby", sr: 5 }
  ], 

  "꒧": [ 
    { c: "ꑘ", p: "nyop", sr: 0 },
    { c: "ꅔ", p: "ndip", sr: 1 },
    { c: "ꇺ", p: "ki", sr: 1 },
    { c: "ꎂ", p: "rro", sr: 2 },
    { c: "ꇊ", p: "lop", sr: 3 },
    { c: "ꁽ", p: "nbat", sr: 4 },
    { c: "ꃍ", p: "fit", sr: 4 }
  ], 

  "꒨": [ 
    { c: "ꄲ", p: "tu", sr: 0 },
    { c: "ꏿ", p: "qip", sr: 1 },
    { c: "ꆪ", p: "hlep", sr: 1 },
    { c: "ꐎ", p: "qu", sr: 1 },
    { c: "ꉻ", p: "ho", sr: 1 },
    { c: "ꊸ", p: "ca", sr: 1 },
    { c: "ꋂ", p: "ce", sr: 1 },
    { c: "ꆩ", p: "hle", sr: 1 },
    { c: "ꐑ", p: "qur", sr: 2 },
    { c: "ꃪ", p: "vat", sr: 2 },
    { c: "ꌷ", p: "sso", sr: 2 },
    { c: "ꆺ", p: "lip", sr: 2 },
    { c: "ꑙ", p: "nyut", sr: 2 },
    { c: "ꇥ", p: "gap", sr: 2 },
    { c: "ꇵ", p: "gup", sr: 2 },
    { c: "ꏰ", p: "jut", sr: 2 },
    { c: "ꌻ", p: "ssep", sr: 2 },
    { c: "ꊶ", p: "cat", sr: 2 },
    { c: "ꇎ", p: "lut", sr: 3 },
    { c: "ꐋ", p: "qop", sr: 3 },
    { c: "ꎔ", p: "nrat", sr: 3 },
    { c: "ꀧ", p: "bo", sr: 3 },
    { c: "ꂮ", p: "mit", sr: 3 },
    { c: "ꂳ", p: "mie", sr: 3 },
    { c: "ꇩ", p: "guop", sr: 4 },
    { c: "ꌆ", p: "nzyp", sr: 4 },
    { c: "ꂔ", p: "hmip", sr: 4 },
    { c: "ꂦ", p: "hmup", sr: 5 }
  ], 

  "꒩": [ 
    { c: "ꂷ", p: "ma", sr: 1 },
    { c: "ꆧ", p: "hlop", sr: 1 },
    { c: "ꆞ", p: "hlat", sr: 1 },
    { c: "ꌡ", p: "sup", sr: 1 },
    { c: "ꀒ", p: "op", sr: 1 },
    { c: "ꆂ", p: "nie", sr: 1 },
    { c: "ꀺ", p: "pi", sr: 1 },
    { c: "ꀜ", p: "bie", sr: 1 },
    { c: "ꊴ", p: "cie", sr: 1 },
    { c: "ꏏ", p: "ro", sr: 1 },
    { c: "ꏉ", p: "rap", sr: 1 },
    { c: "ꀝ", p: "biep", sr: 1 },
    { c: "ꄍ", p: "dot", sr: 1 },
    { c: "ꆰ", p: "hlur", sr: 2 },
    { c: "ꁙ", p: "bbip", sr: 2 },
    { c: "ꈲ", p: "mgat", sr: 2 },
    { c: "ꀄ", p: "iet", sr: 2 },
    { c: "ꆤ", p: "hluop", sr: 2 },
    { c: "ꆚ", p: "hlip", sr: 2 },
    { c: "ꅵ", p: "hnuo", sr: 2 },
    { c: "ꉩ", p: "ngo", sr: 2 },
    { c: "ꋀ", p: "cop", sr: 2 },
    { c: "ꊿ", p: "co", sr: 2 },
    { c: "ꊙ", p: "zuo", sr: 2 },
    { c: "ꆉ", p: "nuop", sr: 2 },
    { c: "ꀑ", p: "o", sr: 2 },
    { c: "ꍕ", p: "zhut", sr: 2 },
    { c: "ꏓ", p: "rep", sr: 2 },
    { c: "ꀖ", p: "bit", sr: 2 },
    { c: "ꋉ", p: "cur", sr: 2 },
    { c: "ꊢ", p: "zut", sr: 2 },
    { c: "ꎟ", p: "nrut", sr: 2 },
    { c: "ꈿ", p: "mgep", sr: 2 },
    { c: "ꏫ", p: "juop", sr: 2 },
    { c: "ꄰ", p: "tut", sr: 2 },
    { c: "ꀚ", p: "biet", sr: 2 },
    { c: "ꐌ", p: "qut", sr: 3 },
    { c: "ꉍ", p: "hxiep", sr: 3 },
    { c: "ꀽ", p: "pie", sr: 3 },
    { c: "ꆊ", p: "not", sr: 3 },
    { c: "ꏈ", p: "ra", sr: 3 },
    { c: "ꀇ", p: "iep", sr: 3 },
    { c: "ꍤ", p: "chap", sr: 3 },
    { c: "ꋠ", p: "zze", sr: 3 },
    { c: "ꐷ", p: "njie", sr: 3 },
    { c: "ꏨ", p: "juot", sr: 3 },
    { c: "ꋄ", p: "cut", sr: 3 },
    { c: "ꁆ", p: "pot", sr: 3 },
    { c: "ꂇ", p: "nbu", sr: 3 },
    { c: "ꑦ", p: "xuo", sr: 3 },
    { c: "ꁖ", p: "bbit", sr: 3 },
    { c: "ꁤ", p: "bbuop", sr: 4 },
    { c: "ꌋ", p: "si", sr: 4 },
    { c: "ꉿ", p: "hep", sr: 4 },
    { c: "ꂊ", p: "nbur", sr: 4 },
    { c: "ꇲ", p: "gut", sr: 4 },
    { c: "ꂼ", p: "muop", sr: 4 },
    { c: "ꁏ", p: "pur", sr: 4 },
    { c: "ꐊ", p: "qo", sr: 4 },
    { c: "ꂋ", p: "nbyt", sr: 4 },
    { c: "ꉭ", p: "ngep", sr: 4 },
    { c: "ꎖ", p: "nra", sr: 5 },
    { c: "ꍲ", p: "chu", sr: 5 },
    { c: "ꍆ", p: "zhat", sr: 5 },
    { c: "ꍳ", p: "chup", sr: 5 }
  ], 

  "꒪（꒫）": [ 
    { c: "ꈯ", p: "ggur", sr: 1 },
    { c: "ꎤ", p: "nrur", sr: 1 },
    { c: "ꐧ", p: "jjut", sr: 1 },
    { c: "ꎽ", p: "shup", sr: 1 },
    { c: "ꀏ", p: "ot", sr: 1 },
    { c: "ꊛ", p: "zot", sr: 1 },
    { c: "ꀬ", p: "but", sr: 2 },
    { c: "ꄗ", p: "dup", sr: 2 },
    { c: "ꈻ", p: "mgo", sr: 2 },
    { c: "ꍘ", p: "zhup", sr: 2 },
    { c: "ꑓ", p: "nyuo", sr: 2 },
    { c: "ꀾ", p: "piep", sr: 2 },
    { c: "ꊞ", p: "zop", sr: 2 },
    { c: "ꀎ", p: "uop", sr: 2 },
    { c: "ꈸ", p: "mguop", sr: 2 },
    { c: "ꁚ", p: "bbiet", sr: 2 },
    { c: "ꅥ", p: "ndup", sr: 3 },
    { c: "ꏒ", p: "re", sr: 3 },
    { c: "ꄳ", p: "tup", sr: 3 },
    { c: "ꆜ", p: "hlie", sr: 3 },
    { c: "ꌴ", p: "ssap", sr: 3 },
    { c: "ꆮ", p: "hlup", sr: 3 },
    { c: "ꉴ", p: "hap", sr: 3 },
    { c: "ꈹ", p: "mgot", sr: 3 },
    { c: "ꁸ", p: "nbi", sr: 3 },
    { c: "ꎊ", p: "rru", sr: 4 },
    { c: "ꅧ", p: "ndur", sr: 4 },
    { c: "ꌳ", p: "ssa", sr: 4 },
    { c: "ꉳ", p: "ha", sr: 4 },
    { c: "ꈡ", p: "gguop", sr: 4 },
    { c: "ꂭ", p: "hmyr", sr: 5 },
    { c: "ꐸ", p: "njiep", sr: 5 }
  ], 

  "꒬（꒭、꒮、꒯）": [ 
    { c: "ꁐ", p: "pyt", sr: 0 },
    { c: "ꂽ", p: "mot", sr: 1 },
    { c: "ꂟ", p: "hmot", sr: 1 },
    { c: "ꆀ", p: "nip", sr: 1 },
    { c: "ꀃ", p: "ip", sr: 1 },
    { c: "ꅠ", p: "nde", sr: 1 },
    { c: "ꁕ", p: "pyr", sr: 2 },
    { c: "ꋒ", p: "zzi", sr: 2 },
    { c: "ꀸ", p: "pit", sr: 2 },
    { c: "ꐛ", p: "jjip", sr: 2 },
    { c: "ꅊ", p: "ddep", sr: 2 },
    { c: "ꎞ", p: "nrep", sr: 2 },
    { c: "ꏼ", p: "qit", sr: 2 },
    { c: "ꉎ", p: "hxat", sr: 2 },
    { c: "ꑱ", p: "yit", sr: 2 },
    { c: "ꑵ", p: "yiet", sr: 2 },
    { c: "ꃹ", p: "vur", sr: 2 },
    { c: "ꂡ", p: "hmo", sr: 3 },
    { c: "ꅽ", p: "nit", sr: 4 },
    { c: "ꀷ", p: "byr", sr: 5 }
  ], 

  "꒰（꒱、꒲）": [ 
    { c: "ꏂ", p: "shy", sr: 0 },
    { c: "ꉹ", p: "hot", sr: 1 },
    { c: "ꒊ", p: "yyp", sr: 1 },
    { c: "ꃳ", p: "vep", sr: 1 },
    { c: "ꏟ", p: "ryr", sr: 1 },
    { c: "ꈼ", p: "mgop", sr: 2 },
    { c: "ꆭ", p: "hlu", sr: 2 },
    { c: "ꊖ", p: "za", sr: 2 },
    { c: "ꈔ", p: "ggit", sr: 2 },
    { c: "ꀥ", p: "bot", sr: 3 },
    { c: "ꐪ", p: "jjup", sr: 3 },
    { c: "ꊫ", p: "zyp", sr: 3 },
    { c: "ꄥ", p: "tuot", sr: 3 },
    { c: "ꊭ", p: "zyr", sr: 4 },
    { c: "ꄬ", p: "top", sr: 4 }
  ], 

  "꒳（꒴、꒵、꒶、꒷）": [
    { c: "ꏮ", p: "jo", sr: 1 },
    { c: "ꁡ", p: "bbap", sr: 2 },
    { c: "ꇐ", p: "lu", sr: 2 },
    { c: "ꂄ", p: "nbop", sr: 2 },
    { c: "ꏬ", p: "jot", sr: 2 },
    { c: "ꑝ", p: "xit", sr: 2 },
    { c: "ꑣ", p: "xie", sr: 2 },
    { c: "ꑡ", p: "xiet", sr: 2 },
    { c: "ꐯ", p: "jjy", sr: 2 },
    { c: "ꀪ", p: "be", sr: 2 },
    { c: "ꂸ", p: "map", sr: 3 },
    { c: "ꂃ", p: "nbo", sr: 3 },
    { c: "ꋃ", p: "cep", sr: 3 },
    { c: "ꑧ", p: "xot", sr: 3 },
    { c: "ꄃ", p: "dip", sr: 3 },
    { c: "ꁨ", p: "bbop", sr: 3 },
    { c: "ꐵ", p: "njiet", sr: 4 },
    { c: "ꌱ", p: "ssat", sr: 4 },
    { c: "ꋿ", p: "nzu", sr: 4 },
    { c: "ꇪ", p: "got", sr: 4 },
    { c: "ꍅ", p: "ssyr", sr: 4 },
    { c: "ꌀ", p: "nzup", sr: 5 }
  ], 

  "꒸（꒹、꒺、꒻）": [ 
    { c: "ꎿ", p: "shur", sr: 0 },
    { c: "ꃆ", p: "mup", sr: 1 },
    { c: "ꆽ", p: "lie", sr: 1 },
    { c: "ꌏ", p: "siep", sr: 1 },
    { c: "ꊈ", p: "wo", sr: 2 },
    { c: "ꄖ", p: "du", sr: 3 }
  ],

  "꒼（꒽）": [ 
    { c: "ꋌ", p: "cy", sr: 1 },
    { c: "ꉼ", p: "hop", sr: 1 },
    { c: "ꑟ", p: "xi", sr: 1 },
    { c: "ꊪ", p: "zy", sr: 1 },
    { c: "ꄆ", p: "diep", sr: 1 },
    { c: "ꊼ", p: "cuop", sr: 1 },
    { c: "ꏾ", p: "qi", sr: 2},
    { c: "ꊉ", p: "wop", sr: 2},
    { c: "ꁿ", p: "nba", sr: 2},
    { c: "ꀻ", p: "pip", sr: 2},
    { c: "ꅢ", p: "ndut", sr: 2},
    { c: "ꇓ", p: "lur", sr: 2},
    { c: "ꇑ", p: "lup", sr: 2},
    { c: "ꋏ", p: "cyr", sr: 2},
    { c: "ꉤ", p: "nguot", sr: 2},
    { c: "ꏍ", p: "rot", sr: 2},
    { c: "ꏐ", p: "rop", sr: 2},
    { c: "ꋛ", p: "zzap", sr: 3},
    { c: "ꐃ", p: "qiep", sr: 3},
    { c: "ꑤ", p: "xiep", sr: 3},
    { c: "ꍐ", p: "zhop", sr: 3},
    { c: "ꋚ", p: "zza", sr: 4}
  ], 

  "꒾（꒿）": [ 
    { c: "ꊱ", p: "cip", sr: 0 },
    { c: "ꉙ", p: "hxop", sr: 0 },
    { c: "ꂣ", p: "hmut", sr: 1 },
    { c: "ꁒ", p: "py", sr: 1 },
    { c: "ꇾ", p: "kiep", sr: 1 },
    { c: "ꐽ", p: "njo", sr: 1 },
    { c: "ꇻ", p: "kip", sr: 2 },
    { c: "ꅋ", p: "ddut", sr: 2 },
    { c: "ꉈ", p: "hxi", sr: 2 },
    { c: "ꂐ", p: "nbyr", sr: 2 },
    { c: "ꐀ", p: "qiet", sr: 3 },
    { c: "ꐻ", p: "njot", sr: 3 },
    { c: "ꐗ", p: "qyr", sr: 3 }
  ], 

  "꓀（꓁、꓂、꓃）": [ 
    { c: "ꎫ", p: "shat", sr: 0 },
    { c: "ꎵ", p: "shop", sr: 0 },
    { c: "ꈁ", p: "ka", sr: 1 },
    { c: "ꄉ", p: "da", sr: 1 },
    { c: "ꄊ", p: "dap", sr: 1 },
    { c: "ꐒ", p: "qyt", sr: 1 },
    { c: "ꇦ", p: "guot", sr: 1 },
    { c: "ꅳ", p: "hnap", sr: 1 },
    { c: "ꈬ", p: "ggu", sr: 2 },
    { c: "ꁠ", p: "bba", sr: 2 },
    { c: "ꈭ", p: "ggup", sr: 2 },
    { c: "ꇨ", p: "guo", sr: 2 },
    { c: "ꊧ", p: "zur", sr: 2 },
    { c: "ꍯ", p: "che", sr: 2 },
    { c: "ꍰ", p: "chep", sr: 2 },
    { c: "ꉦ", p: "nguo", sr: 2 },
    { c: "ꍨ", p: "chuop", sr: 3 },
    { c: "ꋆ", p: "cu", sr: 3 },
    { c: "ꍭ", p: "chet", sr: 3 }
  ],

  "꓄（꓅）": [
    { c: "ꀤ", p: "buop", sr: 1 },
    { c: "ꅂ", p: "dduo", sr: 1 },
    { c: "ꉉ", p: "hxip", sr: 1 },
    { c: "ꅃ", p: "dduop", sr: 2 },
    { c: "ꄽ", p: "ddat", sr: 2 },
    { c: "ꁻ", p: "nbie", sr: 2 },
    { c: "ꎰ", p: "shuo", sr: 3 },
    { c: "ꃩ", p: "viep", sr: 3 },
    { c: "ꏖ", p: "ru", sr: 3 },
    { c: "ꋖ", p: "zzie", sr: 3 },
    { c: "ꀫ", p: "bep", sr: 3 },
    { c: "ꀨ", p: "bop", sr: 4 },
    { c: "ꄿ", p: "dda", sr: 4 },
    { c: "ꅀ", p: "ddap", sr: 4 },
    { c: "ꋘ", p: "zzat", sr: 5 },
    { c: "ꋔ", p: "zziet", sr: 6 }
  ],

  "꓆": [
    { c: "ꈌ", p: "ke", sr: 1 },
    { c: "ꇭ", p: "gop", sr: 2 },
    { c: "ꋯ", p: "nzi", sr: 3 },
    { c: "ꄣ", p: "ta", sr: 3 },
    { c: "ꃛ", p: "fup", sr: 3 },
    { c: "ꋧ", p: "zzyt", sr: 4 },
  ]
};

var bushou =
  "꒐, ꒑（꒒）, ꒓, ꒔, ꒕, ꒖, ꒗（꒘）, ꒙, ꒚（꒛）, ꒜（꒝、꒞）, ꒟（꒠）, ꒡（꒢、꒣）, ꒤（꒥、꒦）, ꒧, ꒨, ꒩, ꒪（꒫）, ꒬（꒭、꒮、꒯）, ꒰（꒱、꒲）, ꒳（꒴、꒵、꒶、꒷）, ꒸（꒹、꒺、꒻）, ꒼（꒽）, ꒾（꒿）, ꓀（꓁、꓂、꓃）, ꓄（꓅）, ꓆";
